PUT http://localhost:5006/api/users/2c974c2d-8c4d-4084-ae06-27702c8207b4
Content-Type: application/json

{
    "username": "jean_n_louis",
    "email": "jloussd@b9.es",
    "profileImageUrl": "https://ages.fb.gov"
}