PUT http://localhost:5006/api/users/68d6d458-8b1c-458c-b761-f7a21c882c56
Content-Type: application/json

{
    "username": "joseph_W_martinez",
    "email": "jloussd@b9.es",
    "profileImageUrl": "https://images.fb.gov"
}