PUT http://localhost:5006/api/users/4ca38371-1b2f-4fbe-814f-f2bb2bb938ec
Content-Type: application/json

{
    "username": "joseph_martinez",
    "email": "jloussd@b9.es",
    "profileImageUrl": "https://images.fb.gov"
}