POST http://localhost:5006/api/events
Content-Type: application/json

{
    "groupId": "00000000-0000-0000-0000-000000000105",
    "title": "Cooler things no",
    "description": "An annual thing focusing on the latest trends in technology and software development.",
    "location": "De Haan, Belgium",
    "startTime": "2025-06-15T07:00:00Z",
    "endTime": "2025-06-15T15:00:00Z"
}