PUT http://localhost:5006/api/events/df92c80c-b14a-4572-8363-a8fb06305216
Content-Type: application/json

{
    "groupId": "00000000-0000-0000-0000-000000000105",
    "title": "Tech for dummies",
    "description": "An conference with snacks and talks about latest trends in technology and software development.",
    "location": "Malaga, Spain",
    "startTime": "2025-09-19T07:00:00Z",
    "endTime": "2025-09-12T15:00:00Z" 
}